version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - freegpt3.5docs_DB__uri=postgresql://postgres:postgres@db:5432/freegpt3.5docs
      - freegpt3.5docs_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: freegpt3.5docs_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/freegpt3.5docs_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=freegpt3.5docs, freegpt3.5docs_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
